config/routes.rb
Spaceapps::Application.routes.draw do

  get "landing/welcome"
  root  'observations#index'
  get   "observations"                => 'observations#index'
  get   "observations/user/:uid"      => 'observations#user'
  post  "observations/create"         => 'observations#create'
  get   "observations/photo/:id"      => 'observations#photo'
  
  get   "feeds/:fid"                  => 'feeds#index'
  get   "feeds/follow/:fid"           => 'feeds#follow'
  
  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Astrodeo</title>
  <!-- CSS -->
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Economica:400,700", media: "all", "data-turbolinks-track" => true %>
  <!-- JS -->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- META -->
  <%= csrf_meta_tags %>
  <!-- FAVICON -->
  <%= favicon_link_tag "favicon.ico?ver=2", :type => "image/x-icon" %>
</head>
<body>

<!-- HEADER -->
<header class="header">
	<div class="container">

		<h1 class="logo"><a href="/"><i class="fa fa-rocket">&nbsp;</i>Astrodeo!</a></h1>
		<% if current_user %>
		<div class="nav nav-user">
			<label class="fa fa-cog js-menu-trigger"></label>
			<label for="modal-3" class="btn-upload js-btn"><i class="fa fa-arrow-circle-o-up"></i> Upload</label>
		</div>
		<% else %>
		<div class="nav nav-public">
			<label for="modal-1" class="link js-btn">Log in</label>
			<label for="modal-2" class="link link-o js-btn">Sign Up</label>
		</div>
		<% end %>

	</div>
</header>

<%= yield %>

<!-- MODAL: LOGIN -->
<div class="modal">
	<input class="modal-state" id="modal-1" type="checkbox" />
	<div class="modal-window">
		<div class="modal-inner">
			<label class="modal-close" for="modal-1"></label>

			<h1>Log in</h1>
			<p class="body">Welcome back!</p>
			<a href="/auth/twitter" class="btn-social btn-twitter">
				<span class="fa-wrapper"><i class="fa fa-twitter"></i></span> <span class="btn-text">Log in with Twitter</span>
			</a>
			<a href="/auth/google" class="btn-social btn-google">
				<span class="fa-wrapper"><li class="fa fa-google-plus"></li></span> <span class="btn-text">Log in with Google</span>
			</a>
			
		</div>
	</div>
</div>

<!-- MODAL: SIGN UP -->
<div class="modal">
	<input class="modal-state" id="modal-2" type="checkbox" />
	<div class="modal-window">
		<div class="modal-inner">
			<label class="modal-close" for="modal-2"></label>

			<h1>Sign up</h1>			
			<p class="body">Get Started FREE</p>
			<a href="/auth/twitter" class="btn-social btn-twitter">
				<span class="fa-wrapper"><i class="fa fa-twitter"></i></span> <span class="btn-text">Sign up with Twitter</span>
			</a>
			<a href="/auth/google" class="btn-social btn-google">
				<span class="fa-wrapper"><li class="fa fa-google-plus"></li></span> <span class="btn-text">Sign up with Google</span>
			</a>
			<p class="text-tos">By clicking "Sign Up" I agree to Astrodeo's Terms of Service.</p>
		</div>
	</div>
</div>

<!-- MODAL: UPLOAD -->
<div class="modal">
	<input class="modal-state" id="modal-3" type="checkbox" />
	<div class="modal-window">
		<div class="modal-inner">
			<label class="modal-close" for="modal-3"></label>

			<h1>Upload</h1>
			<form method="post" action="/observations/create" enctype="multipart/form-data">
				<label>Image</label>
				<p><input type="file" class="file" name="photo" /></p>
				<label>Right Ascension</label>
				<input type="text" name="observation[right_ascension]" placeholder="Enter right ascension" />
				<label>Declination</label>
				<input type="text" name="observation[declination]" placeholder="Enter declination" />
				<label>Magnitude</label>
				<input type="text" name="observation[magnitude]" placeholder="Enter magnitude" />
				<label>Date Seen (mm/dd/yyyy)</label>
				<input type="text" name="observation[seen]" placeholder="Enter date" />
				<label>Latitude</label>
				<input type="text" name="location[latitude]" placeholder="Enter latitude" />
				<label>Longitude</label>
				<input type="text" name="location[longitude]" placeholder="Enter longitude" />
				<label>Altitude</label>
				<input type="text" name="location[altitude]" placeholder="Enter altitude" />
<!--	TODO add thse labels	<form>
				<p><input type="file" class="file" name="" /></p>
				<label>Date Seen</label>
				<input type="text" name="" placeholder="Enter date seen" />
				<label>Catalog Reference</label>
				<input type="text" name="" placeholder="Enter catalog reference" />
				<label>Right Ascension</label>
				<input type="text" name="" placeholder="Enter right ascension" />
				<label>Declination</label>
				<input type="text" name="" placeholder="Enter declination" />
				<label>Magnitude</label>
				<input type="text" name="" placeholder="Enter magnitude" />
-->
				<input class="button" type="submit" value="Finish" />
			</form>

		</div>
	</div>
</div>
<% if current_user %>
<!-- MODAL: PROFILE -->
<div class="modal">
	<input class="modal-state" id="modal-4" type="checkbox" />
	<div class="modal-window">
		<div class="modal-inner">
			<label class="modal-close" for="modal-4"></label>

			<h1>Profile</h1>
			<form>
				<label for="field-fullname">Full name</label>
				<input type="text" name="" id="field-fullname" placeholder="Enter name" value="<%= current_user.name %>" />
				<label for="field-username">Username</label>
				<input type="text" name="" id="field-username" value="<%= current_user.username %>" readonly />
				<input class="button" type="submit" value="Save" />
			</form>

		</div>
	</div>
</div>

<nav class="js-menu sliding-menu-content">
  <ul>
	<li><a><%= current_user.username %></a></li>
    <li><label for="modal-4" class="js-btn"><a>Edit profile</a></label></li>
    <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
  </ul>
</nav>

<% end %>
<div class="js-menu-screen menu-screen"></div>

<script type="text/javascript">	

	  $(document).ready(function(){
	
	    $('.js-menu-trigger').on('click touchstart', function(e){
	      $('.js-menu').toggleClass('is-visible');
	      $('.js-menu-screen').toggleClass('is-visible');
	      e.preventDefault();
	    });
	
	    $('.js-menu-screen').on('click touchstart', function(e){
	      $('.js-menu').toggleClass('is-visible');
	      $('.js-menu-screen').toggleClass('is-visible');
	      e.preventDefault();
	    });
	  });

	$(document).on('keyup', function(e) {
		if (e.keyCode == 27) {
			$(document).find('.modal .modal-state:checked').click();
		}
	});

</script>

</body>
</html>